sources:
  - "./UFO/ScienceGothic[CTRS,slnt,wdth,wght].designspace"
axisOrder:
  - CTRS
  - slnt
  - wdth
  - wght
familyName: "Science Gothic"
logLevel: INFO
cleanUp: true
buildVariable: true
buildStatic: false
buildSmallCap: true
splitItalic: false
outputDir: "../fonts"
vfDir: "../fonts/variable"
ttDir: "../fonts/static"
version: 1.024
stat:
  - name: Weight
    tag: wght
    values:
      - name: Thin
        value: 100
        flags: 0
      - name: Regular
        value: 400
        flags: 0
      - name: Bold
        value: 700
        flags: 0
  - name: Width
    tag: wdth
    values:
      - name: Condensed
        value: 75
        flags: 0
      - name: Normal
        value: 100
        flags: 0
      - name: Expanded
        value: 125
        flags: 0
  - name: Slant
    tag: slnt
    values:
      - name: Upright
        value: 0
        flags: 0
      - name: Slanted
        value: -10
        flags: 0
  - name: Contrast
    tag: CNTR
    values:
      - name: Low
        value: 0
        flags: 0
      - name: Medium
        value: 50
        flags: 0
      - name: High
        value: 100
        flags: 0